services:

  payment-system:

    build:
      context: ./payment-system
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: dev

    container_name: payment-system-api

    
  frontend:

    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "5173:80"

    depends_on:
      - payment-system

    environment:
      - REACT_APP_API_URL=http://payment-system:8080

    container_name: frontend-app